// Mocks generated by Mockito 5.4.6 from annotations
// in subman/test/mocks/mock_in_app_purchase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:in_app_purchase/in_app_purchase.dart' as _i4;
import 'package:in_app_purchase_android/billing_client_wrappers.dart' as _i3;
import 'package:in_app_purchase_android/in_app_purchase_android.dart' as _i7;
import 'package:in_app_purchase_platform_interface/in_app_purchase_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDetailsResponse_0 extends _i1.SmartFake
    implements _i2.ProductDetailsResponse {
  _FakeProductDetailsResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingClientManager_1 extends _i1.SmartFake
    implements _i3.BillingClientManager {
  _FakeBillingClientManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingResultWrapper_2 extends _i1.SmartFake
    implements _i3.BillingResultWrapper {
  _FakeBillingResultWrapper_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseVerificationData_3 extends _i1.SmartFake
    implements _i2.PurchaseVerificationData {
  _FakePurchaseVerificationData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InAppPurchase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInAppPurchase extends _i1.Mock implements _i4.InAppPurchase {
  MockInAppPurchase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.PurchaseDetails>> get purchaseStream =>
      (super.noSuchMethod(
        Invocation.getter(#purchaseStream),
        returnValue: _i5.Stream<List<_i2.PurchaseDetails>>.empty(),
      ) as _i5.Stream<List<_i2.PurchaseDetails>>);

  @override
  T getPlatformAddition<T extends _i2.InAppPurchasePlatformAddition?>() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlatformAddition,
          [],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #getPlatformAddition,
            [],
          ),
        ),
      ) as T);

  @override
  _i5.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.ProductDetailsResponse> queryProductDetails(
          Set<String>? identifiers) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryProductDetails,
          [identifiers],
        ),
        returnValue: _i5.Future<_i2.ProductDetailsResponse>.value(
            _FakeProductDetailsResponse_0(
          this,
          Invocation.method(
            #queryProductDetails,
            [identifiers],
          ),
        )),
      ) as _i5.Future<_i2.ProductDetailsResponse>);

  @override
  _i5.Future<bool> buyNonConsumable(
          {required _i2.PurchaseParam? purchaseParam}) =>
      (super.noSuchMethod(
        Invocation.method(
          #buyNonConsumable,
          [],
          {#purchaseParam: purchaseParam},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> buyConsumable({
    required _i2.PurchaseParam? purchaseParam,
    bool? autoConsume = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buyConsumable,
          [],
          {
            #purchaseParam: purchaseParam,
            #autoConsume: autoConsume,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> completePurchase(_i2.PurchaseDetails? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #completePurchase,
          [purchase],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> restorePurchases({String? applicationUserName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
          {#applicationUserName: applicationUserName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> countryCode() => (super.noSuchMethod(
        Invocation.method(
          #countryCode,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #countryCode,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [InAppPurchaseAndroidPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockInAppPurchaseAndroidPlatform extends _i1.Mock
    implements _i7.InAppPurchaseAndroidPlatform {
  MockInAppPurchaseAndroidPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.PurchaseDetails>> get purchaseStream =>
      (super.noSuchMethod(
        Invocation.getter(#purchaseStream),
        returnValue: _i5.Stream<List<_i2.PurchaseDetails>>.empty(),
      ) as _i5.Stream<List<_i2.PurchaseDetails>>);

  @override
  _i3.BillingClientManager get billingClientManager => (super.noSuchMethod(
        Invocation.getter(#billingClientManager),
        returnValue: _FakeBillingClientManager_1(
          this,
          Invocation.getter(#billingClientManager),
        ),
      ) as _i3.BillingClientManager);

  @override
  _i5.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.ProductDetailsResponse> queryProductDetails(
          Set<String>? identifiers) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryProductDetails,
          [identifiers],
        ),
        returnValue: _i5.Future<_i2.ProductDetailsResponse>.value(
            _FakeProductDetailsResponse_0(
          this,
          Invocation.method(
            #queryProductDetails,
            [identifiers],
          ),
        )),
      ) as _i5.Future<_i2.ProductDetailsResponse>);

  @override
  _i5.Future<bool> buyNonConsumable(
          {required _i2.PurchaseParam? purchaseParam}) =>
      (super.noSuchMethod(
        Invocation.method(
          #buyNonConsumable,
          [],
          {#purchaseParam: purchaseParam},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> buyConsumable({
    required _i2.PurchaseParam? purchaseParam,
    bool? autoConsume = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buyConsumable,
          [],
          {
            #purchaseParam: purchaseParam,
            #autoConsume: autoConsume,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.BillingResultWrapper> completePurchase(
          _i2.PurchaseDetails? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #completePurchase,
          [purchase],
        ),
        returnValue: _i5.Future<_i3.BillingResultWrapper>.value(
            _FakeBillingResultWrapper_2(
          this,
          Invocation.method(
            #completePurchase,
            [purchase],
          ),
        )),
      ) as _i5.Future<_i3.BillingResultWrapper>);

  @override
  _i5.Future<void> restorePurchases({String? applicationUserName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
          {#applicationUserName: applicationUserName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> countryCode() => (super.noSuchMethod(
        Invocation.method(
          #countryCode,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #countryCode,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> getCountryCode() => (super.noSuchMethod(
        Invocation.method(
          #getCountryCode,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getCountryCode,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [PurchaseDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseDetails extends _i1.Mock implements _i2.PurchaseDetails {
  MockPurchaseDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get productID => (super.noSuchMethod(
        Invocation.getter(#productID),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#productID),
        ),
      ) as String);

  @override
  _i2.PurchaseVerificationData get verificationData => (super.noSuchMethod(
        Invocation.getter(#verificationData),
        returnValue: _FakePurchaseVerificationData_3(
          this,
          Invocation.getter(#verificationData),
        ),
      ) as _i2.PurchaseVerificationData);

  @override
  _i2.PurchaseStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i2.PurchaseStatus.pending,
      ) as _i2.PurchaseStatus);

  @override
  bool get pendingCompletePurchase => (super.noSuchMethod(
        Invocation.getter(#pendingCompletePurchase),
        returnValue: false,
      ) as bool);

  @override
  set status(_i2.PurchaseStatus? _status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          _status,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set error(_i2.IAPError? _error) => super.noSuchMethod(
        Invocation.setter(
          #error,
          _error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set pendingCompletePurchase(bool? _pendingCompletePurchase) =>
      super.noSuchMethod(
        Invocation.setter(
          #pendingCompletePurchase,
          _pendingCompletePurchase,
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProductDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetails extends _i1.Mock implements _i2.ProductDetails {
  MockProductDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#price),
        ),
      ) as String);

  @override
  double get rawPrice => (super.noSuchMethod(
        Invocation.getter(#rawPrice),
        returnValue: 0.0,
      ) as double);

  @override
  String get currencyCode => (super.noSuchMethod(
        Invocation.getter(#currencyCode),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currencyCode),
        ),
      ) as String);

  @override
  String get currencySymbol => (super.noSuchMethod(
        Invocation.getter(#currencySymbol),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currencySymbol),
        ),
      ) as String);
}
